	include "sound/Sonic 2 Clone Driver v2 - Macros.asm"
	include "sound/Sonic 2 Clone Driver v2 - Sound IDs.asm"
	include "sound/Sonic 2 Clone Driver v2 - Compatibility.asm"
	include "sound/Sonic 2 Clone Driver v2 - RAM.asm"
	include "sound/Sonic 2 Clone Driver v2 - Constants.asm"
	include "sound/_smps2asm_inc.asm"
