; PWM Equates
offset :=	SH2_PWMTable
ptrsize :=	4*4
idstart :=	$81

; Knuckles' Chaotix
pwmElectricKick =		SMPS_id(ptr_pwm01)
pwmElectricSnare =		SMPS_id(ptr_pwm02)
pwmSplashCymbal =		SMPS_id(ptr_pwm03)
pwmRideBell =			SMPS_id(ptr_pwm04)
pwmHighTom =			SMPS_id(ptr_pwm05)
pwmMidTom =			SMPS_id(ptr_pwm06)
pwmLowTom =			SMPS_id(ptr_pwm07)
pwmElectricHiHat =		SMPS_id(ptr_pwm08)
pwmCrashCymbal =		SMPS_id(ptr_pwm09)
pwmClap =			SMPS_id(ptr_pwm0A)
pwmAcousticKick =		SMPS_id(ptr_pwm0B)
pwmAcousticSnare =		SMPS_id(ptr_pwm0C)
pwmBell =			SMPS_id(ptr_pwm0D)
pwmFingersSnapping =		SMPS_id(ptr_pwm0E)
pwmCowbell =			SMPS_id(ptr_pwm0F)
pwmHighClick =			SMPS_id(ptr_pwm10)
pwmLowClick =			SMPS_id(ptr_pwm11)
pwmHighBongo =			SMPS_id(ptr_pwm12)
pwmLowBongo =			SMPS_id(ptr_pwm13)
pwmHighTimpani =		SMPS_id(ptr_pwm14)
pwmLowTimpani =			SMPS_id(ptr_pwm15)
pwmSilence =			SMPS_id(ptr_pwm16)
